### ISSUE TITLE
ModuleNotFoundError: No module named 'func_timeout'

### ISSUE THREAD

**Issue by ProgramItUp** [lupantech/chameleon-llm#2]
The example on the [main page](https://github.com/lupantech/chameleon-llm) does not seem to work.
Am I missing something?

```
pip install -r requirements.txt
cd run_scienceqa

python run.py \
> --model chameleon \
> --label chameleon_gpt4 \
> --policy_engine gpt-4 \
> --kr_engine gpt-4 \
> --qg_engine gpt-4 \
> --sg_engine gpt-4 \
> --test_split test \
> --test_number -1
Traceback (most recent call last):
  File "/home/marc/code/chameleon-llm/run_scienceqa/run.py", line 11, in <module>
    from utilities import *
  File "/home/marc/code/chameleon-llm/utilities.py", line 4, in <module>
    import func_timeout
ModuleNotFoundError: No module named 'func_timeout'
```

**Comment by lupantech** [comment]
Hi, 

Thanks for pointing it out. The `requirements.txt` file has been fixed by adding the `func_timeout ` package. 

Best regards, 
Pan
